"""add new curpos

Revision ID: 3f3ae7021049
Revises: 40086ee5005b
Create Date: 2020-09-30 14:06:42.868126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3ae7021049'
down_revision = '40086ee5005b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('curpos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'curpos')
    # ### end Alembic commands ###
