"""remove curpos

Revision ID: 40086ee5005b
Revises: f5ca91336081
Create Date: 2020-09-30 14:06:03.961422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40086ee5005b'
down_revision = 'f5ca91336081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'curpos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('curpos', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
