"""seen_cards field

Revision ID: 63252c881ac3
Revises: 3a4b44ba89c7
Create Date: 2020-10-04 21:48:24.085785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63252c881ac3'
down_revision = '3a4b44ba89c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('seen_cards', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'seen_cards')
    # ### end Alembic commands ###
