"""b,e,c places

Revision ID: ac21c8cec1d4
Revises: b8bd98ac87ba
Create Date: 2020-10-10 12:18:01.553294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac21c8cec1d4'
down_revision = 'b8bd98ac87ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('b_places', sa.String(), nullable=True))
    op.add_column('user', sa.Column('c_places', sa.String(), nullable=True))
    op.add_column('user', sa.Column('e_places', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'e_places')
    op.drop_column('user', 'c_places')
    op.drop_column('user', 'b_places')
    # ### end Alembic commands ###
