"""tour selection field

Revision ID: b7c9c8536ad6
Revises: 93dc6938b735
Create Date: 2020-09-25 21:49:39.947649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c9c8536ad6'
down_revision = '93dc6938b735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sel_tour', sa.String(), nullable=False, server_default='1'))
    #op.drop_index('idx_user_curpos', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('idx_user_curpos', 'user', ['curpos'], unique=False)
    op.drop_column('user', 'sel_tour')
    # ### end Alembic commands ###
