"""miss_turn field

Revision ID: b8bd98ac87ba
Revises: ab3a7a9862b6
Create Date: 2020-10-07 15:56:22.815225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bd98ac87ba'
down_revision = 'ab3a7a9862b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_turn', sa.Column('miss_turn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_turn', 'miss_turn')
    # ### end Alembic commands ###
