"""won game_over fields

Revision ID: bda4e0bd267c
Revises: ac21c8cec1d4
Create Date: 2020-10-16 16:50:22.926077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda4e0bd267c'
down_revision = 'ac21c8cec1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_turn', sa.Column('game_over', sa.String(), nullable=True))
    op.add_column('user_turn', sa.Column('won', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_turn', 'won')
    op.drop_column('user_turn', 'game_over')
    # ### end Alembic commands ###
