"""card score

Revision ID: c0e1a2f849a4
Revises: d62652c91fcb
Create Date: 2020-10-02 21:31:41.933189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e1a2f849a4'
down_revision = 'd62652c91fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('score', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'score')
    # ### end Alembic commands ###
