"""card model

Revision ID: d62652c91fcb
Revises: 3f3ae7021049
Create Date: 2020-10-01 17:12:30.435796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62652c91fcb'
down_revision = '3f3ae7021049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('more_info', sa.String(), nullable=True),
    sa.Column('tour', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
